#!/bin/sh
# PJBridge init configuration

# The JDBC driver entry point
export DRIVER=""

# The port the bridge will listen on
export PORT="4444"

# This should point to a JRE/JDK
export JAVA_HOME="/usr/lib/jvm/java-1.6.0"

# The user the bridge will run as
RUNAS_USER="pjbridge"

# Install directory
WORKING_DIR="/opt/pjbridge"
